spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/${DB_NAME:event_db}
    username: ${DB_USER:mediatheque}
    password: ${DB_PASSWORD:mediatheque}
  grpc:
    client:
      channels:
        user-service:
          address: user-service:9091
        mediatheque-service:
          address: mediatheque-service:9090
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
