spring:
  application:
    name: event-service
  profiles:
    active: dev
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  grpc:
    client:
      channels:
        user-service:
          address: localhost:9091
        mediatheque-service:
          address: localhost:9090

server:
  port: 8082

logging:
  level:
    com.events: DEBUG
    org.hibernate.SQL: DEBUG
